# Plugin configuration file for ${name} v${version}

# Localization language
language: en-US

# enabled worlds list
# if this list is empty, all worlds will be added to the enabled worlds list
# otherwise, only listed worlds will be added to the enabled worlds list

#enabled-worlds:
#  - enabled_world1
#  - enabled_world2

# disabled worlds list
# these worlds will be removed from the enabled worlds list created by the previous setting

disabled-worlds:
  - disabled_world1
  - disabled_world2

# Destroy compass on drop
destroy-on-drop: true

# Prevent placing death compass in chests or other containers
no-chest: true

# delay setting compass target after respawn (in ticks; 20 ticks = 1 second)
target-delay: 20

# play sound effects
sound-effects: true
